//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockEscape.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Create_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Create_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LockEscape.Pages._Create.de-DE", typeof(_Create_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Gruppen.
        /// </summary>
        internal static string AmountGroups {
            get {
                return ResourceManager.GetString("AmountGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Rätsel.
        /// </summary>
        internal static string AmountRiddles {
            get {
                return ResourceManager.GetString("AmountRiddles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code mit Rechtsklick kopieren oder einen Screenshot machen!.
        /// </summary>
        internal static string CopyQrCodeMessage {
            get {
                return ResourceManager.GetString("CopyQrCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Spiel erstellen.
        /// </summary>
        internal static string CreateNewGame {
            get {
                return ResourceManager.GetString("CreateNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lehrerpasswort.
        /// </summary>
        internal static string CreatorPassword {
            get {
                return ResourceManager.GetString("CreatorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel bearbeiten.
        /// </summary>
        internal static string EditGame {
            get {
                return ResourceManager.GetString("EditGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spielsprache.
        /// </summary>
        internal static string GameLanguage {
            get {
                return ResourceManager.GetString("GameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiellösung Gruppe.
        /// </summary>
        internal static string GameSolutionGroup {
            get {
                return ResourceManager.GetString("GameSolutionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rätsel Lösung.
        /// </summary>
        internal static string RiddleSolution {
            get {
                return ResourceManager.GetString("RiddleSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanne mich.
        /// </summary>
        internal static string ScanMe {
            get {
                return ResourceManager.GetString("ScanMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur QR Code anzeigen.
        /// </summary>
        internal static string ShowOnlyQr {
            get {
                return ResourceManager.GetString("ShowOnlyQr", resourceCulture);
            }
        }
    }
}
