//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EscapeGames.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.EscapeGames.Errors._Errors", typeof(_Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not be empty..
        /// </summary>
        internal static string CreatorPasswordMustNotBeEmptyErrorMessage {
            get {
                return ResourceManager.GetString("CreatorPasswordMustNotBeEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game solution for groups must not be empty..
        /// </summary>
        internal static string GameSolutionForGroupsMustNotBeEmptyErrorMessage {
            get {
                return ResourceManager.GetString("GameSolutionForGroupsMustNotBeEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game solution must not be empty..
        /// </summary>
        internal static string GameSolutionMustNotBeEmptyErrorMessage {
            get {
                return ResourceManager.GetString("GameSolutionMustNotBeEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group number must be at least 1..
        /// </summary>
        internal static string GroupNumberMustBeAtLeastOneErrorMessage {
            get {
                return ResourceManager.GetString("GroupNumberMustBeAtLeastOneErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid culture provided..
        /// </summary>
        internal static string InvalidCultureErrorMessage {
            get {
                return ResourceManager.GetString("InvalidCultureErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one riddle..
        /// </summary>
        internal static string RiddlesMustNotBeEmptyErrorMessage {
            get {
                return ResourceManager.GetString("RiddlesMustNotBeEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riddle solutions must only contain digits (0-9)..
        /// </summary>
        internal static string RiddleSolutionInvalidFormatErrorMessage {
            get {
                return ResourceManager.GetString("RiddleSolutionInvalidFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riddle solution must have length {0}..
        /// </summary>
        internal static string RiddleSolutionInvalidLengthErrorMessage {
            get {
                return ResourceManager.GetString("RiddleSolutionInvalidLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riddle solutions must not be empty..
        /// </summary>
        internal static string RiddleSolutionMustNotBeEmptyErrorMessage {
            get {
                return ResourceManager.GetString("RiddleSolutionMustNotBeEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected group number is not configured..
        /// </summary>
        internal static string SelectGroupNumberIsNotAvailableErrorMessage {
            get {
                return ResourceManager.GetString("SelectGroupNumberIsNotAvailableErrorMessage", resourceCulture);
            }
        }
    }
}
